### ISSUE TITLE
About Dockerfile?

### ISSUE THREAD

**Issue by anubhavsinha98** [tapasweni-pathak/Dockerfiles#1]
What is actually a Dockerfile ? I searched  a lot but I am not able to find !

**Comment by tapaswenipathak** [comment]
I added links in the readme which has a lot of useful information about Docker and Dockerfile. I'll try to update this ticket and readme with simpler explanation about Docker and Dockerfiles.

**Comment by anubhavsinha98** [comment]
Okay @tapasweni-pathak thanks!
